name: Print Job Summary
on:
  push:
    branches:
      - '**'
jobs:
  Test-GitHub-Job-Summary:
    strategy:
      matrix:
        os: [ ubuntu,macos ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.1
          cache: false
# Use this action to see results in GitHub Actions UI
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # Defined at top level as we use local CLI for testings
          JFROG_CLI_LOG_LEVEL: INFO
          JF_URL: "https://soleng.jfrog.io"
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JFROG_CLI_CURATION: true
        
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'asafambar/npm-example'
          ref: 'main'
        
      - name: run npm install
        run: |
         jf npm-config --repo-resolve=asafa-npm-remote
         jf npm install
        env:
          # Defined at top level as we use local CLI for testings
          JFROG_CLI_LOG_LEVEL: INFO
          JF_URL: "https://soleng.jfrog.io"
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JFROG_CLI_CURATION: true
